apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: disk-test-worker-disk-throughput
  labels:
    app: disk-test-worker-disk-throughput
spec:
  serviceName: disk-test-worker-disk-throughput
  replicas: 3
  selector:
    matchLabels:
      app: disk-test-worker-disk-throughput
  template:
    metadata:
      labels:
        app: disk-test-worker-disk-throughput
        csl-bench.io/scrape: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: disk-test-worker-disk-throughput
              topologyKey: kubernetes.io/hostname
      containers:
        - name: csl-bench
          image: bernhard97/csl-bench:0.4.0
          args:
            - benchmark
            - -d
            - "0"
            - -m
            - disk
            - --io_file_path
            - /data/bench-data
            - --io_file_size
            - "1gb"
          ports:
            - name: metrics
              containerPort: 9090
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          emptyDir: {}
