apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: disk-baseline-volume-transactional
  labels:
    app: disk-baseline-volume-transactional
spec:
  serviceName: disk-baseline-volume-transactional
  replicas: 3
  selector:
    matchLabels:
      app: disk-baseline-volume-transactional
  template:
    metadata:
      labels:
        app: disk-baseline-volume-transactional
        csl-bench.io/scrape: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: disk-baseline-volume-transactional
              topologyKey: kubernetes.io/hostname
      containers:
        - name: csl-bench
          image: bernhard97/csl-bench:0.4.0
          args:
            - baseline
            - -d
            - "300"
            - -m
            - disk
            - --io_mode
            - txn_rw
            - --io_file_path
            - /data/bench-data
            - --io_file_size
            - "1gb"
            - --io_read_bps
            - "10mb"
            - --io_write_bps
            - "10mb"
          ports:
            - name: metrics
              containerPort: 9090
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
